[versions]

# Notepad
notepad-versionCode = "112"
notepad-versionName = "2.3.7"

# Android SDK
android-compileSdk = "31"
android-gradlePlugin = "7.1.2"
android-minSdk = "21"
android-targetSdk = "31"

# AndroidX / Jetpack
androidx-activity = "1.4.0"
androidx-core = "1.7.0"
androidx-datastore = "1.0.0"
androidx-lifecycle = "2.4.1"
androidx-preference = "1.2.0"
androidx-documentfile = "1.0.1"
androidx-localbroadcastmanager = "1.0.0"

# Other dependencies (red-pill app)
accompanist = "0.23.0"
compose = "1.1.0"
composePreferences = "0.1.4"
coroutines = "1.6.0"
koin = "3.2.0-beta-1"
kotlin = "1.6.10"
linkifyText = "0a45dbcf9b"
richtext = "0.11.0"
sqldelight = "1.5.3"
versionsPlugin = "0.42.0"

# Other dependencies (blue-pill app)
appcompat = "1.4.1"
commonsLang = "3.12.0"
markdownView = "1.1.0"
material = "1.5.0"

##################################################################################################################################

[libraries]

# Gradle Plugins
gradle-android = { module = "com.android.tools.build:gradle", version.ref = "android-gradlePlugin" }
gradle-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
gradle-sqldelight = { module = "com.squareup.sqldelight:gradle-plugin", version.ref = "sqldelight" }

# AndroidX / Jetpack
androidx-activity = { module = "androidx.activity:activity-ktx", version.ref = "androidx-activity" }
androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-datastore = { module = "androidx.datastore:datastore-preferences", version.ref = "androidx-datastore" }
androidx-preference = { module = "androidx.preference:preference-ktx", version.ref = "androidx-preference" }
androidx-documentfile = { module = "androidx.documentfile:documentfile", version.ref = "androidx-documentfile" }
androidx-localbroadcastmanager = { module = "androidx.localbroadcastmanager:localbroadcastmanager", version.ref = "androidx-localbroadcastmanager" }

# Compose
compose-activity = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
compose-koin = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin" }
compose-material = { module = "androidx.compose.material:material", version.ref = "compose" }
compose-material-icons = { module = "androidx.compose.material:material-icons-extended", version.ref = "compose" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
compose-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }

# Coroutines
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-sqldelight = { module = "com.squareup.sqldelight:coroutines-extensions", version.ref = "sqldelight" }

# Koin
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }

# RichText
richtext-commonmark = { module = "com.halilibo.compose-richtext:richtext-commonmark", version.ref = "richtext" }
richtext-printing = { module = "com.halilibo.compose-richtext:printing", version.ref = "richtext" }

# Other dependencies (red-pill app)
composePreferences = { module = "com.github.Sh4dowSoul.ComposePreferences:preferences-material", version.ref = "composePreferences" }
linkifyText = { module = "com.github.firefinchdev:linkify-text", version.ref = "linkifyText" }
sqldelight = { module = "com.squareup.sqldelight:android-driver", version.ref = "sqldelight" }
systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }

# Other dependencies (blue-pill app)
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
commonsLang = { module = "org.apache.commons:commons-lang3", version.ref = "commonsLang" }
markdownView = { module = "us.feras.mdv:markdownview", version.ref = "markdownView" }
material = { module = "com.google.android.material:material", version.ref = "material" }

##################################################################################################################################

[bundles]

androidx = [
    "androidx-activity",
    "androidx-core",
    "androidx-datastore",
    "androidx-preference",
    "androidx-documentfile",
    "androidx-localbroadcastmanager"
]

compose = [
    "compose-activity",
    "compose-foundation",
    "compose-koin",
    "compose-material",
    "compose-material-icons",
    "compose-ui",
    "compose-ui-tooling-preview",
    "compose-viewmodel"
]

coroutines = [
    "coroutines-android",
    "coroutines-core",
    "coroutines-sqldelight"
]

koin = [
    "koin-android",
    "koin-core"
]

richtext = [
    "richtext-commonmark",
    "richtext-printing"
]